# Generated by Django 2.2.24 on 2024-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('domain', models.BooleanField(default=True)),
            ],
        ),
    ]
